name: Build IG with publisher version

on:
  workflow_call:
    inputs:
      ig-root:
        required: true
        type: string
      publisher-args:
        required: true
        type: string
      docker-tag:
        required: true
        type: string
      io-repo:
        type: string
      io-branch:
        type: string
        default: gh-pages
      io-path:
        type: string
    secrets:
      io-token:
        required: true
jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ig
      - name: Docker build
        run: |
          echo Running IG build
          mkdir -p "${GITHUB_WORKSPACE}/ig/${{inputs.ig-root}}/output"
          echo hello > "${GITHUB_WORKSPACE}/ig/${{inputs.ig-root}}/output/index.html"
          #docker pull "sessaid/ig-publisher:${{inputs.docker-tag}}"
          #docker run --rm --volume "${GITHUB_WORKSPACE}/ig/${{inputs.ig-root}}:/ig" "sessaid/ig-publisher:${{inputs.docker-tag}}"  ${{ inputs.publisher-args }}

      # Publish if requested
      - name: Checkout IO
        if: inputs.io-repo != ''
        uses: actions/checkout@v3
        with:
          path: io
          repository: ${{inputs.io-repo}}
          ref: ${{ inputs.io-branch }}
          token: ${{ secrets.io-token }}

      - name: Publish IO
        if: inputs.io-repo != ''
        run: |
          set -x
          env | sort
          rm -rf "${GITHUB_WORKSPACE}/io/${{ inputs.io-path }}"
          mkdir -p "${GITHUB_WORKSPACE}/io/${{ inputs.io-path }}"
          cp -ra "${GITHUB_WORKSPACE}/ig/${{inputs.ig-root}}/output" "${GITHUB_WORKSPACE}/io/${{ inputs.io-path }}"
          cd "${GITHUB_WORKSPACE}/io"
          git config --global user.name 'Publisher IO'
          git config --global user.email 'shahim@essaid.com'
          git add -A
          git commit -m "Publisher IO -GHB"
          cat .git/config
          git remote set-url origin "https://github.com/${{inputs.io-repo}}"
          git push

          
