name: Build IG with publisher version
on:
  workflow_call:
    inputs:
      hello:
        required: true
        type: string
      publisher-version:
        required: true
        type: string
jobs:
  ig-build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: "echo Hello: ${{ inputs.hello }}"