name: Build IG with publisher version

on:
  workflow_call:
    inputs:
      ig-root:
        required: true
        type: string
      publisher-args:
        required: true
        type: string
      docker-tag:
        required: true
        type: string
jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.ig-root }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: |
          docker pull "sessaid/ig-publisher:${{inputs.docker-tag}}"
          docker run --volume "${GITHUB_WORKSPACE}/${{inputs.ig-root}}:/ig-root" "sessaid/ig-publisher:${{inputs.docker-tag}}"  ${{ inputs.publisher-args }}
          
