name: Build IG with publisher version

on:
  workflow_call:
    inputs:
      ig-root:
        required: true
        type: string
      publisher-args:
        required: true
        type: string
      docker-tag:
        required: true
        type: string
      io-repo:
        type: string
      io-path:
        type: string
jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ig
      - name: Docker build
        run: |
          echo Running IG build
          #docker pull "sessaid/ig-publisher:${{inputs.docker-tag}}"
          #docker run --rm --volume "${GITHUB_WORKSPACE}/ig/${{inputs.ig-root}}:/ig" "sessaid/ig-publisher:${{inputs.docker-tag}}"  ${{ inputs.publisher-args }}
      - name: Checkout IO
        if: inputs.io-repo != ''
        run: |
          echo checking out IO repo ${{ inputs.io-repo }} with path ${{ inputs.io-path }}
        

          
